# Generated by Django 5.0.2 on 2024-03-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projects_vote_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
